name: Run Property Alert Filter

on:
  schedule:
    - cron: '15 13 * * *'  # Runs at 13:15 UTC daily (15:15 Johannesburg)
  workflow_dispatch:        # Allows manual trigger from the UI

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4

      - name: Debug env
        run: echo "EMAIL is $EMAIL"
        env:
          EMAIL: ${{ secrets.EMAIL }}

      - name: Run script
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: python property_alert_filter.py
